### PR TITLE
Added general language support and translation to German

### PR DESCRIPTION
**Pull request by JustFxDev**
Hi there,

i just added Language Support to Kanboard-DueDate, some minor changes and german translation files.

This is my first attempt to contribute to a git project. I hope this works and furthermore it helps to improve things.

Kind regards, Fx

### CODE REVIEW

**Comment by dmorlitz** [comment]
I am no longer using Kanboard on my system (not because of anything
Kanboard related - just that my needs changed) so i am not going to be able
to test this code change.

You are welcome to take over this code to keep it maintained for newer
Kanboard versions, if you want.

I actually have other plugins you would be welcome to maintain, if you
want. Most of them are less complicated than this one.

**Comment by dmorlitz** [comment]
Merged language support

**Comment by JustFxDev** [comment]
Hi @dmorlitz,

i can take over and try my best. I'am not a php guy, but i think i'am good in programming. Just let me know how a take over could be arranged and there we go.

Cheers, fx

**Comment by dmorlitz** [comment]
Since you already have a kanboard-duedate repository, which matches mine exactly, you can just keep maintaining it there.  You can also submit a pull request to the https://github.com/kanboard/website repo that updates the URL and ownership name on the kanboard-duedate plugin to your repository (this will update the Kanboard web-site)

If you have questions on the PHP code as you maintain it, please feel free to reach out.  I really like Kanboard and I am happy to help support it.  It is just that the project I was using Kanboard on has ended and I don't have a need for it at this time, which is why my development environment has gotten disabled.

**Comment by JustFxDev** [comment]
Ok, lets do it that way. Fine for me. I just do not want to "take over" things without any permission / agreement.

Would you mind to do the changes regarding the Kanboard website? If so anyone can see: it is done with permission of the owner.

And if there are any questions i will come back gladly to your offer (without straining it ;-)

Thanks! fx

**Comment by dmorlitz** [comment]
I have updated the website plugins.json file and submitted the Pull Request - this should update the Kanboard Plugins site with your name and repository.  I have updated the README.md file in my repository to point to your as well - so you should be "fully" in control.

**Comment by JustFxDev** [comment]
Sounds good!

Thanks for your trust. Feel free to change that every time.

Happy holidays and a good start into the new year!

Cheers, fx

**Pull request merged**
